
// This file was auto-generated by ML.NET Model Builder. 

using MLModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input


Console.WriteLine("enter Review type\n\n");

string review = Console.ReadLine();
MLModel.ModelInput sampleData = new MLModel.ModelInput()
{
    ReviewType = review,
    // ReviewType = @"1",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Review with predicted Review from sample data...\n\n");


Console.WriteLine($"Review: {@"Improper Dress"}");
Console.WriteLine($"ReviewType: {@"1"}");


var sortedScoresWithLabel = MLModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

